gpus: [1]
save_path: saved_fb15k
load_path: null
seed: 1
num_iters: 1

data:
  data_path: ../data/fb15k
  rule_file: ../data/fb15k/fb15k_rules_invabd_filteraug.txt
  batch_size: 4

predictor:
  model:
    type: emb
    num_layers: 3
    hidden_dim: 16
    entity_feature: RotatE
    aggregator: pna
    embedding_path: ../data/fb15k/RotatE_500
    rel_weight: 0.05
  optimizer:
    lr: 0.005
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 1000000
    print_every: 1
  eval:
    expectation: True
    
