gpus: [2]
save_path: saved_umls
load_path: null
seed: 1
num_iters: 1

data:
  data_path: ../data/umls
  rule_file: ../data/umls/umls_rules.txt
  batch_size: 32

predictor:
  model:
    type: emb
    num_layers: 3
    hidden_dim: 16
    entity_feature: RotatE
    aggregator: pna
    embedding_path: ../data/umls/RotatE_1000
    rel_weight: 0.1
  optimizer:
    lr: 0.005
    weight_decay: 0
  train:
    smoothing: 0.2
    batch_per_epoch: 1000000
    print_every: 1
  eval:
    expectation: True
    
